// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordQuest.Infrastructure;

#nullable disable

namespace WordQuest.Infrastructure.Migrations
{
    [DbContext(typeof(WordQuestDbContext))]
    partial class WordQuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_card");

                    b.HasIndex("EntryId", "Direction")
                        .IsUnique()
                        .HasDatabaseName("ix_card_entry_id_direction");

                    b.ToTable("card", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.VocabularyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("ExampleSource")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("example_source");

                    b.Property<string>("ExampleTarget")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("example_target");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("part_of_speech");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.PrimitiveCollection<string[]>("SourceAlternatives")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("source_alternatives");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_text");

                    b.PrimitiveCollection<string[]>("TargetAlternatives")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("target_alternatives");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary_entry");

                    b.HasIndex("SetId", "Position")
                        .HasDatabaseName("ix_vocabulary_entry_set_id_position");

                    b.ToTable("vocabulary_entry", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.VocabularySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("source_language");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("target_language");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary_set");

                    b.HasIndex("TenantId", "Title")
                        .HasDatabaseName("ix_vocabulary_set_tenant_id_title");

                    b.ToTable("vocabulary_set", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Gamification.Entities.GamificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("date")
                        .HasColumnName("last_active_date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<int>("MasteredSinceLastCard")
                        .HasColumnType("integer")
                        .HasColumnName("mastered_since_last_card");

                    b.Property<string>("StreakSaverPeriod")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("streak_saver_period");

                    b.Property<int>("StreakSaversLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("streak_savers_left");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_gamification_profile");

                    b.ToTable("gamification_profile", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.LearnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("avatar_key");

                    b.Property<int>("DailyNewLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("daily_new_limit");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_pin_attempts");

                    b.Property<string>("PinHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTimeOffset?>("PinLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_locked_until");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sound_enabled");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("speed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_learner_profile");

                    b.ToTable("learner_profile", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_user_id_expires_at");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequirePinEverySession")
                        .HasColumnType("boolean")
                        .HasColumnName("require_pin_every_session");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_tenant_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("ix_app_user_tenant_id_role");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.LearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoinsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("coins_awarded");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("game_key");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("learner_id");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id")
                        .HasName("pk_learning_session");

                    b.HasIndex("LearnerId", "StartedAt")
                        .HasDatabaseName("ix_learning_session_learner_id_started_at");

                    b.ToTable("learning_session", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.ReviewLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnswerMs")
                        .HasColumnType("integer")
                        .HasColumnName("answer_ms");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("game_key");

                    b.Property<string>("GivenAnswer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("given_answer");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("learner_id");

                    b.Property<double>("ResultingIntervalDays")
                        .HasColumnType("double precision")
                        .HasColumnName("resulting_interval_days");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_review_log");

                    b.HasIndex("LearnerId", "CardId")
                        .HasDatabaseName("ix_review_log_learner_id_card_id");

                    b.HasIndex("LearnerId", "ReviewedAt")
                        .HasDatabaseName("ix_review_log_learner_id_reviewed_at");

                    b.ToTable("review_log", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.ReviewState", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("learner_id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5)
                        .HasColumnName("ease_factor");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<double>("IntervalDays")
                        .HasColumnType("double precision")
                        .HasColumnName("interval_days");

                    b.Property<int>("Lapses")
                        .HasColumnType("integer")
                        .HasColumnName("lapses");

                    b.Property<string>("LastGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("last_grade");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("LearnerId", "CardId")
                        .HasName("pk_review_state");

                    b.HasIndex("LearnerId", "DueAt")
                        .HasDatabaseName("ix_review_state_learner_id_due_at");

                    b.HasIndex("LearnerId", "State")
                        .HasDatabaseName("ix_review_state_learner_id_state");

                    b.ToTable("review_state", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.SessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AnswerMs")
                        .HasColumnType("integer")
                        .HasColumnName("answer_ms");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid?>("ClientAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_answer_id");

                    b.Property<string>("GivenAnswer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("given_answer");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retry");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_session_item");

                    b.HasIndex("ClientAnswerId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_item_client_answer_id")
                        .HasFilter("client_answer_id IS NOT NULL");

                    b.HasIndex("SessionId", "Position")
                        .HasDatabaseName("ix_session_item_session_id_position");

                    b.ToTable("session_item", (string)null);
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.Card", b =>
                {
                    b.HasOne("WordQuest.Modules.Content.Entities.VocabularyEntry", "Entry")
                        .WithMany("Cards")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_vocabulary_entry_entry_id");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.VocabularyEntry", b =>
                {
                    b.HasOne("WordQuest.Modules.Content.Entities.VocabularySet", "Set")
                        .WithMany("Entries")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vocabulary_entry_vocabulary_set_set_id");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.LearnerProfile", b =>
                {
                    b.HasOne("WordQuest.Modules.Identity.Entities.User", "User")
                        .WithOne("LearnerProfile")
                        .HasForeignKey("WordQuest.Modules.Identity.Entities.LearnerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_profile_app_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.SessionItem", b =>
                {
                    b.HasOne("WordQuest.Modules.Learning.Entities.LearningSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_item_learning_session_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.VocabularyEntry", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("WordQuest.Modules.Content.Entities.VocabularySet", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("WordQuest.Modules.Identity.Entities.User", b =>
                {
                    b.Navigation("LearnerProfile");
                });

            modelBuilder.Entity("WordQuest.Modules.Learning.Entities.LearningSession", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
